Polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('poll.urls'))
]

poll/urls.py
from . import views
from django.urls import path
app_name= "poll"
urlpatterns = [
    path('' ,views.index, name='index'),
    path('choices/<int:question_id>/', views.detail , name="detail"),
    path('<int:question_id>/results/', views.results, name="results"),
    path('<int:question_id>/vote', views.vote , name="vote"),
]

poll/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default = timezone.now)

    class Meta:
        verbose_name_plural = "Questions"

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    question  = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Choices"

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def index(request):
    latest_question = Question.objects.order_by('-pub_date')[:4]
    return render(request, 'poll/index.html', {'questions':latest_question})


def detail(request ,question_id):
    details = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'questions':details})

def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'questions':question})



def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError , Choice.DoesNotExist):
        error = True
        return render(request, 'poll/detail.html', {'questions':question, 'error_message':error})
    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question_id,)))

poll/templates/poll/detail.html
<h1>Please vote </h1>

{% if error_message %}
<p><strong>Invalid Choice..Please choose again</strong></p>
{% endif %}
{% if questions %}
<form action="{% url 'poll:vote' questions.id %}" method="post">
  {% csrf_token %}
{% for q in questions.choice_set.all %}
<p><input type="radio" name="choice" value="{{ q.id }}" >{{q.choice_text}}</p>

{% endfor %}
<input type="submit">
</form>
{% else %}
<p>No Choices  available</p>
{% endif %}

poll/templates/poll/index.html
{% if questions %}
{% for q in questions %}
<p><li><a href="{% url 'poll:detail' q.id %}">{{q.question_text}}</a></li><p>

{% endfor %}

{% else %}
<p>No questions available</p>
{% endif %}

poll/templates/poll/results.html
<h1>Results of following choice </h1>

{% if questions %}
{% for q in questions.choice_set.all %}
<li>{{q.choice_text}}--{{q.vote}} vote{{q.vote|pluralize}}
{% endfor %}

{% else %}
<p>No results available</p>
{% endif %}